### ISSUE TITLE
Using talkback-toggle-tile with a custom accessiblity app

### ISSUE THREAD

**Issue by Scherady** [ataulm/talkback-toggle-tile#4]
Dear all,

I am developing an accessibility app for visually impaired persons. I need to enable/disable TalkBack from my app. 

Can I use talkback-toggle-tile to do it?
If yes how should I proceed?

Thank you.

Kind regards
Brian

**Comment by ataulm** [comment]
Hi Brian - I'm not sure whether it's possible, but you can try.

You'll need to declare the WRITE_SECURE_SETTINGS permission in your manifest:

```xml
    <uses-permission android:name="android.permission.WRITE_SECURE_SETTINGS"
        tools:ignore="ProtectedPermissions" />
```

and also ask the user for permission explicitly: 

- https://developer.android.com/guide/topics/permissions/overview#special_permissions
- https://developer.android.com/reference/android/Manifest.permission#WRITE_SETTINGS

Then see this file:

- https://github.com/ataulm/talkback-toggle-tile/blob/master/mobile/src/main/java/com/ataulm/talkbacktile/Toggler.java

Good luck!

**Comment by Scherady** [comment]
Hi Ataulm,

Thank you for your reply.

1.
You'll need to declare the WRITE_SECURE_SETTINGS permission in your manifest

Do I also need to have:

$ adb shell pm grant com.ataulm.talkbacktile android.permission.WRITE_SECURE_SETTINGS

run for every device?


2. 
From a coding point of view, how do I integrate talkback-toggle-tile in my application? Import it as a new module or other? 


3.
How do I call enableTalkBack() and disableTalkBack() from my application.

Thank you
Brian

**Comment by ataulm** [comment]
1.  I don't think so. The user will be granting this permission (see the links)
2. /3 You can't include this in your app - it's not a library, it's a standalone application in its own right. You can use that class I linked/this project as a reference.
