### ISSUE TITLE
Detecting EditText field while Talkback is enabled

### ISSUE THREAD

**Issue by Scherady** [ataulm/talkback-toggle-tile#5]
Hi,

I am using talkback-toggle-tile and it is working fine.

Now I need to disable Talkback when the user touches an EditText field while Talkback is enabled, what do you recommend?

Thank you.

**Comment by ataulm** [comment]
hey, this sounds like the tile is being used outside of the intended scope.

Apps should not be turning TalkBack on/off on behalf of the user. This project (talkback-toggle-tile) is _for_ developers while they're developing.

Maybe I've misunderstood your question?

**Comment by Scherady** [comment]
I am developing an app for blind people, with a new type of keyboard for blind persons. The user, uses Talkback to navigate and when an EditText filed is reached my app keyboard should appear, therefore I need to know when an EditText field is entred.

**Comment by ataulm** [comment]
Ah ok, that sounds interesting. I wonder if you could register the app as an IME input option so that the user can just choose your keyboard to appear instead of the default one.

In any case, this issue isn't related to this project so I'd recommend asking on StackOverflow and perhaps the [Eyes-Free Google Group](https://groups.google.com/forum/#!forum/eyes-free).

**Comment by Scherady** [comment]
Yes exactly I have registered my app as an additional IME and the user is able to choose my keyboard to appear instead of the default one and it is working fine. 

I am using  talkback-toggle-tile service to enable/disable Talkback and it is working fine.

I have also another AccessibiltyService that detects when an EditText is touched and it is working fine.

The problem is talkback-toggle-tile service and my Accessibility Service cannot co-exist; when one is enabled the other is disabled ! 

What to do ?
